# Generated by Django 4.1.2 on 2022-11-03 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_app', '0004_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_key', models.IntegerField(default=0)),
                ('userA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.author'),
        ),
        migrations.AlterField(
            model_name='response',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.author'),
        ),
    ]
