# Generated by Django 4.1.2 on 2022-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_advertisement_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='upload',
            field=models.FileField(default=None, upload_to='upload/'),
        ),
    ]
