# Generated by Django 4.1.2 on 2022-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0009_alter_advertisement_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='upload',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
