# Generated by Django 4.1.2 on 2022-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0011_alter_advertisement_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
